### ISSUE TITLE
Don't rely on external CDNs

### ISSUE THREAD

**Issue by ghost** [minora-oss/nodebb-plugin-camo#11]
Your plugin appears to be loading javascript contents at runtime from `cdn.jsdelivr.net`.

This is very bad because:

- external CDNs can go down
- external CDNs can get hacked: modules included at runtime from external CDNs won't go through proper cryptographic checks or at least someone verifying the downloaded code hasn't been tampered with if the CDN was hacked or compromised
- external CDNs can get overloaded and lead to surprising hidden slowdowns that can be challenging to track down

.. and most importantly, **because this dependency is not obvious** and therefore shouldn't be there. There is no easy way to find out which sort of plethora of CDNs NodeBB and its plugins depends on for proper operation, so if a big forum hoster uses a CDN of their own for NodeBB they can get huge reliability issues even if they take care that their own CDN remains available. Also since you appear to have included this in the plugin settings this will break the admin area, which is not exactly a good area to break. Therefore, the only reliable way is to package things properly at install/packaging time, instead of loading stuff from external sources at runtime.

Edit: a small note: this only happens for me on the plugins settings page for your plugin. If it's not actually originating from your plugin I apologize for the rant, but it's not easy to see where the require.js call actually originates from. (another reason why the world would be better off if people stopped randomly pulling in things from external CDNs)

**Comment by yariplus** [comment]
Thanks for reporting. Definitely agree.
