### ISSUE TITLE
Proxying already secure images doesn't work with integrated Camo.

### ISSUE THREAD

**Issue by yariplus** [minora-oss/nodebb-plugin-camo#3]
Proxying an image that is already https doesn't actually work. I have no clue why.

**Comment by yariplus** [comment]
It **does** parse the url correctly, so I don't think that's the issue.

**Comment by lenovouser** [comment]
@yariplus you are using the integrated camo, right? Because it works for me with external camo on [minora.io/community/test-https-image](https://minora.io/community/topic/1/welcome-to-your-nodebb/10)

**Comment by yariplus** [comment]
Only happens when you don't provide the fullchain in SSL configs.
