### ISSUE TITLE
Add test scripts

### ISSUE THREAD

**Issue by yariplus** [minora-oss/nodebb-plugin-camo#5]
I don't really know how to do this, but it's something I want for all my plugins eventually.

**Comment by bdharrington7** [comment]
For some inspiration, if you'd like: https://github.com/bdharrington7/nodebb-plugin-imgbed/blob/master/test/test.js

**Comment by yariplus** [comment]
Thanks ! :+1:

**Comment by yariplus** [comment]
Got it working good now. Thanks for the inspiration.
